### PR TITLE
Hotfix/users in room

### PR DESCRIPTION
**Pull request by remote-event**
The issue is fixed when a username that was added thru the api was not being removed when the user has left the room.

### CODE REVIEW

**Comment by remote-event** [comment]
I need assistance.

**Comment by dnguyen00** [comment]
sir get good

**Comment by remote-event** [comment]
> 
> 
> sir get good

How come Khai-san doesn't touch me.

**Comment by khai93** [comment]
Random test failed because there was an update the nodejs runtime "crypto" module where they updated the maxInt value form UInt32 to Int32.

https://github.com/nodejs/node/commit/993ed19f9c9da7bec66298f02643ea5efaa8c7fd

**Comment by remote-event** [comment]
```
C:\Users\Khai93\Desktop\sync\node_modules\coveralls\bin\coveralls.js:19
      throw err;
      ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
(Use `node --trace-uncaught ...` to show where the exception was thrown)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Review by khai93 — APPROVED** [review]
checked

**Pull request merged**
